name: Database Backup

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install PostgreSQL 17 client  
      run: |
        # Add PostgreSQL official APT repository
        curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update
        
        # Install PostgreSQL 17 client
        sudo apt-get install -y postgresql-client-17
        
        # Verify version
        pg_dump --version
        
    - name: Create backup directory
      run: mkdir -p backups
      
    - name: Create database backup
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        BACKUP_DATE=$(date +'%Y%m%d_%H%M%S')
        BACKUP_FILE="backups/backup_${BACKUP_DATE}.sql"
        
        # Use PostgreSQL 17 pg_dump
        pg_dump "$DATABASE_URL" > "$BACKUP_FILE"
        gzip "$BACKUP_FILE"
        
        echo "Backup created: ${BACKUP_FILE}.gz"
        
    - name: Upload backup as artifact
      uses: actions/upload-artifact@v4
      with:
        name: database-backup-${{ github.run_number }}
        path: backups/*.gz
        retention-days: 30
        
    - name: List current backups
      run: |
        echo "Available backups:"
        ls -la backups/
        
    - name: Cleanup old local backups
      run: |
        find backups -name "*.gz" -mtime +7 -delete || true
