name: Database Backup

on:
  schedule:
    # รันทุกวันเวลา 02:00 UTC (09:00 เวลาไทย)
    - cron: '0 2 * * *'
  workflow_dispatch: # อนุญาตให้รันด้วยตนเองได้

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        
    - name: Create backup directory
      run: mkdir -p backups
      
    - name: Create database backup
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        # สร้างชื่อไฟล์ backup ตามวันที่
        BACKUP_DATE=$(date +'%Y%m%d_%H%M%S')
        BACKUP_FILE="backups/backup_${BACKUP_DATE}.sql"
        
        # Export database
        pg_dump "$DATABASE_URL" > "$BACKUP_FILE"
        
        # บีบอัดไฟล์เพื่อประหยัดพื้นที่
        gzip "$BACKUP_FILE"
        
        echo "Backup created: ${BACKUP_FILE}.gz"
        
    - name: Upload backup as artifact
      uses: actions/upload-artifact@v4
      with:
        name: database-backup-${{ github.run_number }}
        path: backups/*.gz
        retention-days: 30 # เก็บไฟล์ 30 วัน
        
    - name: List current backups
      run: |
        echo "Available backups:"
        ls -la backups/
        
    - name: Cleanup old local backups
      run: |
        # ลบไฟล์ที่เก่ากว่า 7 วัน (ถ้ามี)
        find backups -name "*.gz" -mtime +7 -delete || true